# Generated by Django 5.0.1 on 2024-03-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobile',
            name='category',
            field=models.CharField(choices=[('scooty', 'scooty'), ('SUPER', 'super'), ('bike', 'bike')], max_length=20),
        ),
    ]
